# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit learningtower.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      error = FALSE)


## ----loadlibraries------------------------------------------------------------
library(rjtools)
library(learningtower)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(patchwork)
library(viridis)
library(plotly)
library(ggplot2)


## ----gendergap, fig.height = 14, fig.width = 6, fig.align = "center", fig.pos="H"----

student_2018 <- load_student("2018")
data(countrycode)

student_country <- left_join(student_2018, countrycode, by = "country")


#removing na values
math_pisa_2018_data <- student_country %>% 
  filter(!is.na(gender)) %>% 
  filter(!is.na(math)) %>% 
  filter(!is.na(stu_wgt)) 


#avg math scores and diff 
math_diff_df <- math_pisa_2018_data %>%
group_by(gender, country_name) %>%
summarise(avg = weighted.mean(math, stu_wgt)) %>%
ungroup() %>%
pivot_wider(country_name, names_from = gender,
values_from = avg) %>%
mutate(diff = female - male,
country_name = fct_reorder(country_name, diff))



#Bootstrap using R: Part 1
set.seed(2020) # for reproducibility
boot_sample1_math <- math_pisa_2018_data %>%
group_by(country_name, gender) %>%
sample_n(size = n(), replace = TRUE)

boot_sample1_df_math <- boot_sample1_math %>%
summarise(avg = weighted.mean(math, stu_wgt)) %>%
ungroup() %>%
pivot_wider(country_name, names_from = gender, values_from = avg) %>%
mutate(diff = female - male, country_name = fct_reorder(country_name, diff))

#Bootstrap using R: Part 2
boot_ests_math <- map_dfr(1:100, ~{
math_pisa_2018_data %>%
group_by(country_name, gender) %>%
sample_n(size = n(), replace = TRUE) %>%
summarise(avg = weighted.mean(math, stu_wgt)) %>%
ungroup() %>%
pivot_wider(country_name, names_from = gender, values_from = avg) %>%
mutate(diff = female - male, country_name = fct_reorder(country_name, diff)) %>%
mutate(boot_id = .x)
})

#Bootstrap using R: Part 3
math_diff_conf_intervals <- boot_ests_math %>%
group_by(country_name) %>%
summarise(lower = sort(diff)[5],
upper = sort(diff)[95])%>%
left_join(math_diff_df, by = "country_name") %>%
mutate(country_name = fct_reorder(country_name, diff)) %>% 
mutate(score_class = ifelse(diff < 0, 'red', 'blue'))


math_plot <- ggplot(math_diff_conf_intervals, 
                    aes(diff, country_name, 
                        col = score_class)) +
geom_point() +
geom_errorbar(aes(
xmin = lower,
xmax = upper)) +
geom_vline(xintercept = 0, color = "red") +
labs(y = "",
x = "Maths Scores Girls - Boys", 
title = "Maths") +
 theme(legend.position="none")


## -----------------------------------------------------------------------------
#removing na values
read_pisa_2018_data <- student_country %>% 
  filter(!is.na(gender)) %>% 
  filter(!is.na(read)) %>% 
  filter(!is.na(stu_wgt)) 

#avg math scores and diff 
read_diff_df <- read_pisa_2018_data %>%
group_by(gender, country_name) %>%
summarise(avg = weighted.mean(read, stu_wgt)) %>%
ungroup() %>%
pivot_wider(country_name, names_from = gender,
values_from = avg) %>%
mutate(diff = female - male,
country_name = fct_reorder(country_name, diff))




#Bootstrap using R: Part 1
set.seed(2020) # for reproducibility
boot_sample1_read <- read_pisa_2018_data %>%
group_by(country_name, gender) %>%
sample_n(size = n(), replace = TRUE)

boot_sample1_df_read <- boot_sample1_read %>%
summarise(avg = weighted.mean(read, stu_wgt)) %>%
ungroup() %>%
pivot_wider(country_name, names_from = gender, values_from = avg) %>%
mutate(diff = female - male, country_name = fct_reorder(country_name, diff))

#Bootstrap using R: Part 2
boot_ests_read <- map_dfr(1:100, ~{
read_pisa_2018_data %>%
group_by(country_name, gender) %>%
sample_n(size = n(), replace = TRUE) %>%
summarise(avg = weighted.mean(read, stu_wgt)) %>%
ungroup() %>%
pivot_wider(country_name, names_from = gender, values_from = avg) %>%
mutate(diff = female - male, country_name = fct_reorder(country_name, diff)) %>%
mutate(boot_id = .x)
})

#Bootstrap using R: Part 3
read_diff_conf_intervals <- boot_ests_read %>%
group_by(country_name) %>%
summarise(lower = sort(diff)[5],
upper = sort(diff)[95])%>%
left_join(read_diff_df, by = "country_name") %>%
mutate(country_name = fct_reorder(country_name, diff)) %>% 
mutate(score_class = ifelse(diff < 0, 'red', 'blue'))


read_plot <- ggplot(read_diff_conf_intervals, 
                    aes(diff, country_name, 
                        col = score_class)) +
geom_point() +
geom_errorbar(aes(
xmin = lower,
xmax = upper)) +
geom_vline(xintercept = 0, color = "red") +
labs(y = "",
x = "Reading Scores Girls - Boys", 
title = "Reading") +
 theme(legend.position="none")


## -----------------------------------------------------------------------------
#removing na values
sci_pisa_2018_data <- student_country %>% 
  filter(!is.na(gender)) %>% 
  filter(!is.na(science)) %>% 
  filter(!is.na(stu_wgt)) 

#avg math scores and diff 
sci_diff_df <- sci_pisa_2018_data %>%
group_by(gender, country_name) %>%
summarise(avg = weighted.mean(science, stu_wgt)) %>%
ungroup() %>%
pivot_wider(country_name, names_from = gender,
values_from = avg) %>%
mutate(diff = female - male,
country_name = fct_reorder(country_name, diff))




#Bootstrap using R: Part 1
set.seed(2020) # for reproducibility
boot_sample1_sci <- sci_pisa_2018_data %>%
group_by(country_name, gender) %>%
sample_n(size = n(), replace = TRUE)

boot_sample1_df_sci <- boot_sample1_sci %>%
summarise(avg = weighted.mean(science, stu_wgt)) %>%
ungroup() %>%
pivot_wider(country_name, names_from = gender, values_from = avg) %>%
mutate(diff = female - male, country_name = fct_reorder(country_name, diff))

#Bootstrap using R: Part 2
boot_ests_sci <- map_dfr(1:100, ~{
sci_pisa_2018_data %>%
group_by(country_name, gender) %>%
sample_n(size = n(), replace = TRUE) %>%
summarise(avg = weighted.mean(science, stu_wgt)) %>%
ungroup() %>%
pivot_wider(country_name, names_from = gender, values_from = avg) %>%
mutate(diff = female - male, country_name = fct_reorder(country_name, diff)) %>%
mutate(boot_id = .x)
})

#Bootstrap using R: Part 3
sci_diff_conf_intervals <- boot_ests_sci %>%
group_by(country_name) %>%
summarise(lower = sort(diff)[5],
upper = sort(diff)[95])%>%
left_join(sci_diff_df, by = "country_name") %>%
mutate(country_name = fct_reorder(country_name, diff))%>% 
mutate(score_class = ifelse(diff < 0, 'red', 'blue'))


sci_plot <- ggplot(sci_diff_conf_intervals, 
                    aes(diff, country_name, 
                        col = score_class)) +
geom_point() +
geom_errorbar(aes(
xmin = lower,
xmax = upper)) +
geom_vline(xintercept = 0, color = "red") +
labs(y = "",
x = "Science Scores Girls - Boys", 
title = "Science") +
 theme(legend.position="none")


## ----score-differences, fig.cap ="Gender Analysis", fig.width=12, fig.height=16, fig.pos = "H", out.width="100%", layout="l-body"----
math_plot + read_plot + sci_plot


## -----------------------------------------------------------------------------
theme_map <- function(...) {
  theme_minimal() +
  theme(
    text = element_text(),
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    ...
  )
}


## -----------------------------------------------------------------------------
math_map_data <- math_diff_conf_intervals %>% 
  dplyr::mutate(country_name = case_when(
                country_name == "Brunei Darussalam" ~ "Brunei",
                country_name == "United Kingdom" ~ "UK",
                country_name %in% c("Macau SAR China", "B-S-J-Z (China)", 
                                    "Hong Kong SAR China") ~ "China",
                country_name == "Korea" ~ "South Korea",
                country_name == "North Macedonia" ~ "Macedonia",
                country_name == "Baku (Azerbaijan)" ~ "Baku",
                country_name %in% c("Moscow Region (RUS)", "Tatarstan (RUS)",
                "Russian Federation") ~ "Russia",
                country_name == "Slovak Republic" ~ "Slovakia",
                country_name == "Chinese Taipei" ~ "Taiwan",
                country_name == "United States" ~ "USA",
                TRUE ~ as.character(country_name)))

world_map <- map_data("world") %>% 
  filter(region != "Antarctica") %>% 
  fortify() %>% 
  rename(country_name = region)

math_world_data <- full_join(math_map_data,
                        world_map,
                        by = "country_name") 

math_world_data <- math_world_data %>% 
  rename(Country = country_name, 
         `Maths Scores Girls - Boys` = diff)


math_map_plot <- ggplot(math_world_data, 
                        aes(x = long, y = lat, group = group)) +
                  geom_polygon(aes(fill= `Maths Scores Girls - Boys`, 
                                   label = Country)) +
                  theme_map() +
                  labs(title = "World Map displaying Maths Scores Difference") +
                  scale_fill_viridis(option = "D")


## -----------------------------------------------------------------------------
# Maps in R - Reading Maps
read_map_data <- read_diff_conf_intervals %>% 
  dplyr::mutate(country_name = case_when(
                country_name == "Brunei Darussalam" ~ "Brunei",
                country_name == "United Kingdom" ~ "UK",
                country_name %in% c("Macau SAR China", "B-S-J-Z (China)", 
                                    "Hong Kong SAR China") ~ "China",
                country_name == "Korea" ~ "South Korea",
                country_name == "North Macedonia" ~ "Macedonia",
                country_name == "Baku (Azerbaijan)" ~ "Baku",
                country_name %in% c("Moscow Region (RUS)", "Tatarstan (RUS)",
                "Russian Federation") ~ "Russia",
                country_name == "Slovak Republic" ~ "Slovakia",
                country_name == "Chinese Taipei" ~ "Taiwan",
                country_name == "United States" ~ "USA",
                TRUE ~ as.character(country_name)))

world_map <- map_data("world") %>% 
  filter(region != "Antarctica") %>% 
  fortify() %>% 
  rename(country_name = region)

read_world_data <- full_join(read_map_data,
                        world_map,
                        by = "country_name") 

read_world_data <- read_world_data %>% 
  rename(Country = country_name, 
         `Reading Scores Girls - Boys` = diff)



read_map_plot <- ggplot(read_world_data, 
                        aes(x = long, y = lat, group = group)) +
                  geom_polygon(aes(fill= `Reading Scores Girls - Boys`, 
                                   label = Country)) +
                  theme_map() +
                  labs(title = "World Map displaying Reading Scores Difference") +
                  scale_fill_viridis(option = "C")


## -----------------------------------------------------------------------------
sci_map_data <- sci_diff_conf_intervals %>% 
  dplyr::mutate(country_name = case_when(
                country_name == "Brunei Darussalam" ~ "Brunei",
                country_name == "United Kingdom" ~ "UK",
                country_name %in% c("Macau SAR China", "B-S-J-Z (China)", 
                                    "Hong Kong SAR China") ~ "China",
                country_name == "Korea" ~ "South Korea",
                country_name == "North Macedonia" ~ "Macedonia",
                country_name == "Baku (Azerbaijan)" ~ "Baku",
                country_name %in% c("Moscow Region (RUS)", "Tatarstan (RUS)",
                "Russian Federation") ~ "Russia",
                country_name == "Slovak Republic" ~ "Slovakia",
                country_name == "Chinese Taipei" ~ "Taiwan",
                country_name == "United States" ~ "USA",
                TRUE ~ as.character(country_name)))

world_map <- map_data("world") %>% 
  filter(region != "Antarctica") %>% 
  fortify() %>% 
  rename(country_name = region)

sci_world_data <- full_join(sci_map_data,
                        world_map,
                        by = "country_name") 

sci_world_data <- sci_world_data %>% 
  rename(Country = country_name, 
         `Science Scores Girls - Boys` = diff)

sci_map_plot <- ggplot(sci_world_data, 
                        aes(x = long, y = lat, group = group)) +
                  geom_polygon(aes(fill= `Science Scores Girls - Boys`, 
                                   label = Country)) +
                  theme_map() +
                  labs(title = "World Map displaying Science Scores Difference") +
                  scale_fill_viridis(option = "G")


## ----plotly_maps, fig.cap="Plotly Maps", fig.pos="H", fig.height=4, fig.width=12, include=knitr::is_html_output(), eval=knitr::is_html_output()----
#> ggplotly(math_map_plot)
#> ggplotly(read_map_plot)
#> ggplotly(sci_map_plot)


## ----ggplot-maps, fig.cap="Maps", fig.height=9, fig.pos="H", include=knitr::is_latex_output(), eval=knitr::is_latex_output()----
math_map_plot/read_map_plot/sci_map_plot

