# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit learningtower.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE, 
                      message = FALSE, 
                      error = FALSE)


## ----loadlibraries------------------------------------------------------------
library(rjtools)
library(learningtower)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(viridis)
library(patchwork)
library(plotly)
library(ggbeeswarm)
library(gganimate)


## ----gendergap----------------------------------------------------------------

# Get the 2018 student data
if (!file.exists("data/student_2018.rda")) {
  student_2018 <- load_student("2018")
  save(student_2018, file = "data/student_2018.rda")
} else {
  load("data/student_2018.rda")
}
data(countrycode, package = "learningtower")

# Load the country names, and join
student_country <- left_join(student_2018, 
                             countrycode, by = "country")

# Drop missing values
math_pisa_2018_data <- student_country %>% 
  filter(!is.na(gender), !is.na(math), !is.na(stu_wgt))

# Compute average math scores and gender diff 
if (!file.exists("data/math_diff_conf_intervals.rda")) {
math_diff_df <- math_pisa_2018_data %>%
  group_by(gender, country_name) %>% 
  summarise(avg = weighted.mean(math, stu_wgt),
            .groups = "drop") %>%
  ungroup() %>%
  pivot_wider(country_name, 
              names_from = gender,
              values_from = avg) %>%
mutate(diff = female - male, 
       country_name = fct_reorder(country_name, diff))

# Compute bootstrap samples 
set.seed(2020)
boot_ests_math <- map_dfr(1:100, ~{
  math_pisa_2018_data %>%
  group_by(country_name, gender) %>%
  sample_n(size = n(), replace = TRUE) %>%
  summarise(avg = weighted.mean(math, stu_wgt), 
            .groups = "drop") %>%
  pivot_wider(country_name, 
              names_from = gender, 
              values_from = avg) %>%
  mutate(diff = female - male, 
         country_name = fct_reorder(country_name, diff)) %>%
  mutate(boot_id = .x) 
})

# Compute bootstrap confidence intervals
math_diff_conf_intervals <- boot_ests_math %>%
  group_by(country_name) %>%
  summarise(lower = sort(diff)[5],
            upper = sort(diff)[95], 
            .groups = "drop") %>%
  left_join(math_diff_df, by = "country_name") %>%
  mutate(country_name = fct_reorder(country_name, diff)) %>%
  mutate(score_class = factor(case_when(
    lower < 0 & upper <= 0 ~ "boys", 
    lower < 0 & upper >= 0 ~ "nodiff",
    lower >= 0 & upper > 0 ~ "girls"),
      levels = c("boys", "nodiff", "girls")))

  save(math_diff_conf_intervals,
       file="data/math_diff_conf_intervals.rda")

} else {
  load("data/math_diff_conf_intervals.rda")
}

# Plot math
math_plot <- ggplot(math_diff_conf_intervals, 
                    aes(diff, country_name, 
                        col = score_class)) +
  scale_colour_manual("",  
      values = c("boys"="#3288bd", 
                 "nodiff"="#969696", 
                 "girls"="#f46d43")) +
  geom_point() + 
  geom_errorbar(aes(xmin = lower, xmax = upper), width=0) +
  geom_vline(xintercept = 0, color = "#969696") +
  labs(y = "",
  x = "", 
  title = "math"
  ) +
  theme(legend.position="none") + 
  annotate("text", x = 50, y = 1, label = "Girls") +
  annotate("text", x = -50, y = 1, label = "Boys") +
  scale_x_continuous(limits = c(-70, 70), 
                     breaks = seq(-60, 60, 20),
                     labels = abs(seq(-60, 60, 20)))


## -----------------------------------------------------------------------------
# Subset data and drop missing values
read_pisa_2018_data <- student_country %>%  
  filter(!is.na(gender)) %>% 
  filter(!is.na(read)) %>% 
  filter(!is.na(stu_wgt)) 

# Compute average math scores and gender diff 
if (!file.exists("data/read_diff_conf_intervals.rda")) {
read_diff_df <- read_pisa_2018_data %>%
  group_by(gender, country_name) %>%
  summarise(avg = weighted.mean(read, stu_wgt), 
            .groups = "drop") %>%
  ungroup() %>%
  pivot_wider(country_name, names_from = gender,
  values_from = avg) %>%
  mutate(diff = female - male,
  country_name = fct_reorder(country_name, diff))

# Compute bootstrap samples 
boot_ests_read <- map_dfr(1:100, ~{
  read_pisa_2018_data %>%
  group_by(country_name, gender) %>%
  sample_n(size = n(), replace = TRUE) %>%
  summarise(avg = weighted.mean(read, stu_wgt), 
            .groups = "drop") %>%
  ungroup() %>%
  pivot_wider(country_name, names_from = gender, values_from = avg) %>%
  mutate(diff = female - male, country_name = fct_reorder(country_name, diff)) %>%
  mutate(boot_id = .x)
})

# Compute bootstrap confidence intervals
read_diff_conf_intervals <- boot_ests_read %>%
  group_by(country_name) %>%
  summarise(lower = sort(diff)[5],
            upper = sort(diff)[95], 
            .groups = "drop")%>%
  left_join(read_diff_df, by = "country_name") %>%
  mutate(country_name = fct_reorder(country_name, diff)) %>%
  mutate(score_class = factor(case_when(
    lower < 0 & upper <= 0 ~ "boys", 
    lower < 0 & upper >= 0 ~ "nodiff",
    lower >= 0 & upper > 0 ~ "girls"),
      levels = c("boys", "nodiff", "girls")))

  save(read_diff_conf_intervals,
       file="data/read_diff_conf_intervals.rda")

} else {
  load("data/read_diff_conf_intervals.rda")
}

read_plot <- ggplot(read_diff_conf_intervals, 
                    aes(diff, country_name, 
                        col = score_class)) +
  scale_colour_manual("",  
      values = c("boys"="#3288bd", 
                 "nodiff"="#969696", 
                 "girls"="#f46d43")) +
  geom_point() + 
  geom_errorbar(aes(xmin = lower, xmax = upper), width=0) +
  geom_vline(xintercept = 0, color = "#969696") +
  labs(y = "",
  x = "", 
  title = "Reading"
  ) +
  theme(legend.position="none") +
  annotate("text", x = 50, y = 1, label = "Girls") +
  annotate("text", x = -50, y = 1, label = "Boys") +
  scale_x_continuous(limits = c(-70, 70), 
                     breaks = seq(-60, 60, 20),
                     labels = abs(seq(-60, 60, 20)))


## -----------------------------------------------------------------------------
# Subset data and drop missing values
sci_pisa_2018_data <- student_country %>% 
  filter(!is.na(gender)) %>% 
  filter(!is.na(science)) %>% 
  filter(!is.na(stu_wgt)) 

# Compute average math scores and gender diff 
if (!file.exists("data/sci_diff_conf_intervals.rda")) {
sci_diff_df <- sci_pisa_2018_data %>%
  group_by(gender, country_name) %>%
  summarise(avg = weighted.mean(science, stu_wgt), 
            .groups = "drop") %>%
  ungroup() %>%
  pivot_wider(country_name, names_from = gender,
  values_from = avg) %>%
  mutate(diff = female - male,
  country_name = fct_reorder(country_name, diff))

# Compute bootstrap samples 
boot_ests_sci <- map_dfr(1:100, ~{
  sci_pisa_2018_data %>%
  group_by(country_name, gender) %>%
  sample_n(size = n(), replace = TRUE) %>%
  summarise(avg = weighted.mean(science, stu_wgt),
    .groups = "drop") %>%
  ungroup() %>%
  pivot_wider(country_name, 
              names_from = gender, 
              values_from = avg) %>%
  mutate(diff = female - male, country_name = fct_reorder(country_name, diff)) %>%
  mutate(boot_id = .x)
})

# Compute bootstrap confidence intervals
sci_diff_conf_intervals <- boot_ests_sci %>%
  group_by(country_name) %>%
  summarise(
    lower = sort(diff)[5],
    upper = sort(diff)[95],
    .groups = "drop")%>%
  left_join(sci_diff_df, by = "country_name") %>%
  mutate(country_name = fct_reorder(country_name, diff)) %>%
  mutate(score_class = factor(case_when(
    lower < 0 & upper <= 0 ~ "boys", 
    lower < 0 & upper >= 0 ~ "nodiff",
    lower >= 0 & upper > 0 ~ "girls"),
      levels = c("boys", "nodiff", "girls")))

  save(sci_diff_conf_intervals,
       file="data/sci_diff_conf_intervals.rda")

} else {
  load("data/sci_diff_conf_intervals.rda")
}


sci_plot <- ggplot(sci_diff_conf_intervals, 
                    aes(diff, country_name, 
                        col = score_class)) +
  scale_colour_manual("",  
      values = c("boys"="#3288bd", 
                 "nodiff"="#969696", 
                 "girls"="#f46d43")) +
  geom_point() + 
  geom_errorbar(aes(xmin = lower, xmax = upper), width=0) +
  geom_vline(xintercept = 0, color = "#969696") +
  labs(y = "",
  x = "", 
  title = "Science"
  ) +
  theme(legend.position="none") + 
  annotate("text", x = 50, y = 1, label = "Girls") +
  annotate("text", x = -50, y = 1, label = "Boys") +
  scale_x_continuous(limits = c(-70, 70), 
                     breaks = seq(-60, 60, 20),
                     labels = abs(seq(-60, 60, 20)))


## ----score-differences, fig.cap ="The chart above depicts the gender gap difference in 15-year-olds' in math, reading, and science results in 2018. The scores to the right of the grey line represent the performances of the girls, while the scores to the left of the grey line represent the performances of the boys. One of the most intriguing conclusions we can get from this chart is that in the PISA experiment in 2018, girls from all countries outperformed boys in reading.", fig.width=11, fig.height=11, fig.pos = "H", out.width="100%", layout="l-body"----
math_plot + read_plot + sci_plot


## -----------------------------------------------------------------------------
theme_map <- function(...) {
  theme_minimal() +
  theme(
    text = element_text(),
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    panel.border = element_blank(),
    panel.grid = element_blank()
  )
}


## -----------------------------------------------------------------------------
math_map_data <- math_diff_conf_intervals  %>% 
  dplyr::mutate(country_name = case_when(
                country_name == "Brunei Darussalam" ~ "Brunei",
                country_name == "United Kingdom" ~ "UK",
                country_name %in% c("Macau SAR China", "B-S-J-Z (China)", 
                                    "Hong Kong SAR China") ~ "China",
                country_name == "Korea" ~ "South Korea",
                country_name == "North Macedonia" ~ "Macedonia",
                country_name == "Baku (Azerbaijan)" ~ "Baku",
                country_name %in% c("Moscow Region (RUS)", "Tatarstan (RUS)",
                "Russian Federation") ~ "Russia",
                country_name == "Slovak Republic" ~ "Slovakia",
                country_name == "Chinese Taipei" ~ "Taiwan",
                country_name == "United States" ~ "USA",
                TRUE ~ as.character(country_name)))

world_map <- map_data("world") %>% 
  filter(region != "Antarctica") %>% 
  fortify() %>% 
  rename(country_name = region)

math_world_data <- full_join(math_map_data,
                        world_map,
                        by = "country_name") 

math_world_data <- math_world_data %>% 
  rename(Country = country_name, 
         math = diff) %>% 
  mutate(math = round(math, digits = 2))


## -----------------------------------------------------------------------------
# Maps in R - Reading Maps
read_map_data <- read_diff_conf_intervals %>% 
  dplyr::mutate(country_name = case_when(
                country_name == "Brunei Darussalam" ~ "Brunei",
                country_name == "United Kingdom" ~ "UK",
                country_name %in% c("Macau SAR China", "B-S-J-Z (China)", 
                                    "Hong Kong SAR China") ~ "China",
                country_name == "Korea" ~ "South Korea",
                country_name == "North Macedonia" ~ "Macedonia",
                country_name == "Baku (Azerbaijan)" ~ "Baku",
                country_name %in% c("Moscow Region (RUS)", "Tatarstan (RUS)",
                "Russian Federation") ~ "Russia",
                country_name == "Slovak Republic" ~ "Slovakia",
                country_name == "Chinese Taipei" ~ "Taiwan",
                country_name == "United States" ~ "USA",
                TRUE ~ as.character(country_name)))

world_map <- map_data("world") %>% 
  filter(region != "Antarctica") %>% 
  fortify() %>% 
  rename(country_name = region)

read_world_data <- full_join(read_map_data,
                        world_map,
                        by = "country_name") 

read_world_data <- read_world_data %>% 
  rename(Country = country_name, 
         Reading = diff) %>% 
  mutate(Reading = round(Reading, digits = 2))


## -----------------------------------------------------------------------------
sci_map_data <- sci_diff_conf_intervals %>% 
  dplyr::mutate(country_name = case_when(
                country_name == "Brunei Darussalam" ~ "Brunei",
                country_name == "United Kingdom" ~ "UK",
                country_name %in% c("Macau SAR China", "B-S-J-Z (China)", 
                                    "Hong Kong SAR China") ~ "China",
                country_name == "Korea" ~ "South Korea",
                country_name == "North Macedonia" ~ "Macedonia",
                country_name == "Baku (Azerbaijan)" ~ "Baku",
                country_name %in% c("Moscow Region (RUS)", "Tatarstan (RUS)",
                "Russian Federation") ~ "Russia",
                country_name == "Slovak Republic" ~ "Slovakia",
                country_name == "Chinese Taipei" ~ "Taiwan",
                country_name == "United States" ~ "USA",
                TRUE ~ as.character(country_name)))

world_map <- map_data("world") %>% 
  filter(region != "Antarctica") %>% 
  fortify() %>% 
  rename(country_name = region)

sci_world_data <- full_join(sci_map_data,
                        world_map,
                        by = "country_name") 

sci_world_data <- sci_world_data %>% 
  rename(Country = country_name, 
         Science = diff)  %>% 
  mutate(Science = round(Science, digits = 2))

math_dat <- math_world_data %>% 
  dplyr::select(Country, math, lat, long, group)

read_dat <- read_world_data %>% 
  dplyr::select(Country, Reading, lat, long, group)

sci_dat <- sci_world_data %>% 
  dplyr::select(Country, Science, lat, long, group)

math_read_dat <- left_join(math_dat,
                           read_dat, 
                           by = c("Country","lat", "long", "group"))

math_read_sci_dat <- left_join(math_read_dat,
                           sci_dat, 
                           by = c("Country","lat", "long", "group"))

math_read_sci_dat_wider <- math_read_sci_dat %>% 
    pivot_longer(cols = c(2,6,7), names_to = "subjects")

mrs_maps <- ggplot(math_read_sci_dat_wider, 
       aes(x = long, 
           y = lat, 
           group = group)) +
  geom_polygon(aes(fill= value,
                   label = Country)) +
  facet_wrap(~subjects, scales = "free", nrow = 3) +
  theme_map() +
  labs(title = "World Map displaying Gender Gap Scores in Math, Reading and Science")  +
  scale_fill_distiller(palette = "Spectral")


## ----plotly-maps, fig.cap="Interactive maps showing the gender gap in math, reading, and science results between girls and boys across the world. The interactive aspect of the map allows one to move their cursor around the global map, which displays the country name as well as the gender gap scores between girls and boys. A positive score for a country indicates that girls outperformed boys in that country, whereas a negative score for a country difference indicates that boys outperformed girls in that country. The diverging colour scale makes it possible to interpret the range of scores and the also helps us intrepret the gender gap difference among these students across the globe. The reading scores all have positive values, indicating that girls outperform boys across the world in the year 2018.", fig.pos="H", fig.height=12, fig.width=18, out.width="100%", layout="l-body", include=knitr::is_html_output(), eval=knitr::is_html_output()----
#> ggplotly(mrs_maps)


## ----ggplot-maps, fig.cap="Maps showing the gender gap in math, reading, and science results between girls and boys throughout the world. The diverging colour scale makes it possible to interpret the range of scores and it also helps us intrepret the gender gap difference among these students across the globe. The legend displayed enables interpretation of the score differential for each subject across all maps. A positive score for a country indicates that girls outperformed boys in that country, whereas a negative score for a country difference indicates that boys outperformed girls in that country.The reading scores are all positive, suggesting that girls outperform boys globally in the year 2018.", fig.height=9, fig.pos="H", out.width="100%", layout="l-body", include=knitr::is_latex_output(), eval=knitr::is_latex_output()----
mrs_maps


## -----------------------------------------------------------------------------
p1 <- ggplot(data = student_country, 
             aes(x = math, y = read)) +
  geom_hex() + 
  labs(x = "Math Scores", 
       y = "Reading Scores") +
  theme(legend.position="none")

p2 <- ggplot(data = student_country, 
             aes(x = math, y = science)) +
  geom_hex() + 
  labs(x = "Math Scores", 
       y = "Science Scores") +
  theme(legend.position = "none")

p3 <- ggplot(data = student_country, 
             aes(x = read, y = science)) +
  geom_hex() + 
  labs(x = "Reading Scores", 
       y = "Science Scores") +
  theme(legend.position="none")


## ----corr-plot, fig.cap ="The scatterplot displays the relationship between math, reading, and science scores for all PISA countries that participated in the experiment in 2018. This scatterplot shows that all three subjects have a significant and positive correlation with one another.", fig.width=9, fig.pos = "H", out.width="100%", layout="l-body"----
p1+p2+p3


## -----------------------------------------------------------------------------
student_country_data <- left_join(student_2018,
                                  countrycode,
                                  by = "country")


father_qual_math_read_sci_data <- student_country_data %>%
  group_by(country_name, father_educ) %>%
  dplyr::summarise(math_avg = weighted.mean(math, w = stu_wgt, na.rm = TRUE),
                   read_avg = weighted.mean(read, w = stu_wgt, na.rm = TRUE),
                   sci_avg  =  weighted.mean(science, w = stu_wgt, na.rm = TRUE)) %>%
dplyr::mutate(father_educ = recode_factor(father_educ,
                "less than ISCED1" = "Early Childhood",
                "ISCED 1" = "Primary",
                "ISCED 2" = "Lower Secondary",
                "ISCED 3A" = "Upper Secondary",
                "ISCED 3B, C" = "Upper Secondary",
                .ordered = TRUE)) %>%
  na.omit() %>%
  rename(`Father's Education` = father_educ)

mother_qual_math_read_sci_data <- student_country_data %>%
  group_by(country_name, mother_educ) %>%
  dplyr::summarise(math_avg = weighted.mean(math, w = stu_wgt, na.rm = TRUE),
                   read_avg = weighted.mean(read, w = stu_wgt, na.rm = TRUE),
                   sci_avg  =  weighted.mean(science, w = stu_wgt, na.rm = TRUE)) %>% 
dplyr::mutate(mother_educ = recode_factor(mother_educ,
                "less than ISCED1" = "Early Childhood",
                "ISCED 1" = "Primary",
                "ISCED 2" = "Lower Secondary",
                "ISCED 3A" = "Upper Secondary",
                "ISCED 3B, C" = "Upper Secondary",
                .ordered = TRUE)) %>%
  na.omit() %>%
  rename(`Mother's Education` = mother_educ)

mother_qual_math <- ggplot(mother_qual_math_read_sci_data, 
       aes(x=`Mother's Education`,
           y=math_avg,
           col=`Mother's Education`)) +
  geom_quasirandom(size = 1.7, 
             cex = 3) +
  geom_line(aes(group = country_name), 
            size=0.5, alpha=.36) +
  scale_fill_viridis(discrete = TRUE,
                     option = "A",
                      alpha=0.2) +
    stat_summary(fun.y = median, 
                 fun.ymin = median, 
                 fun.ymax = median,
                 geom = "crossbar", 
                 width = 0.5, 
                 col = "black") +
  theme(legend.position="none",
      plot.title = element_text(size=11)) +
    labs(y = "Average Mathematics Score",
         x = "Mother's Qualification",
         title = "math Scores and Mother's Qualification")

father_qual_math <- ggplot(father_qual_math_read_sci_data, 
       aes(x=`Father's Education`,
           y=math_avg,
           col=`Father's Education`)) +
  geom_quasirandom(size = 1.7, 
             cex = 3) +
  geom_line(aes(group = country_name), 
            size=0.5, alpha=.36) +
  scale_fill_viridis(discrete = TRUE,
                     option = "A",
                      alpha=0.2) +
    stat_summary(fun.y = median, 
                 fun.ymin = median, 
                 fun.ymax = median,
                 geom = "crossbar", 
                 width = 0.5, 
                 col = "black") +
  theme(legend.position="none",
      plot.title = element_text(size=11)) +
    labs(y = "Average Mathematics Score",
         x = "Father's Qualification",
         title = "math Scores and Father's Qualification")


## ----qual-plot, fig.cap ="The impact of parents' education on their children's academic progress is depicted in this graph. When the parents have greater levels of education, we see a considerable rise in scores and an increase in the median of scores for each category, as shown in the figure. In comparison to parents with lower levels of education qualifications. Parents who have tend to have upper secondary qualification or equivalent credentials their children are more likely to perform better in academics when compared with parent having lesser levels of qualifications.", fig.width= 15, fig.height= 8, fig.pos = "H", out.width="100%", layout="l-body"----
father_qual_math + mother_qual_math


## -----------------------------------------------------------------------------
z_star_95 <- qnorm(0.975) 

tv_math_data <- student_country_data %>% 
  group_by(country_name, television) %>% 
  dplyr::summarise(math_avg = 
                     weighted.mean(math, 
                                   w = stu_wgt, 
                                   na.rm = TRUE), 
                   lower = weighted.mean(math, 
                      w = stu_wgt, na.rm = TRUE) - 
                      z_star_95 * (sd(math, na.rm = TRUE)) /
                      sqrt(length(math)), 
                   upper = weighted.mean(math, 
                      w = stu_wgt, na.rm = TRUE) + 
                      z_star_95 * (sd(math, na.rm = TRUE)) /
                     sqrt(length(math)), 
                   .groups = "drop") %>% 
  #dplyr::mutate(television = recode_factor(television,
  #               "0" = "No TV",
  #               "1" = "1 TVs",
  #               "2" = "2 Tvs",
  #               "3+" = "3+ TVs", 
  #              .ordered = TRUE)) %>%
  na.omit() %>% 
  dplyr::select(country_name, 
                television, 
                math_avg, 
                lower, 
                upper)

linear_model <- function(y, x){
  coef(lm(y ~ x))[2]
}

tv_plot <- tv_math_data %>%
  group_by(country_name) %>%
  mutate(slope = linear_model(math_avg, television)) %>%
  ungroup() %>%
  mutate(country_name = fct_reorder(country_name, slope)) %>%
  ggplot(aes(x=as.numeric(television), y=math_avg)) + 
  geom_ribbon(aes(ymin = lower, ymax = upper),
                colour="orange", fill = "orange", 
              alpha=0.45) +
  geom_point(size=1.8) +
  geom_line() +
  facet_wrap(~country_name, ncol = 8, scales = "free") +
#  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1)) +
  theme(axis.text = element_blank()) +
  labs(x = "Number of TVs",
       y = "Average Mathematics Score")


## ----tv-plot, fig.cap ="The impact of television on student performance is a contentious issue, however in this figure, we examine the effects of television on student performance using statistical methods. The counties are arranged according to the slope of the linear model fitted for the math average score against the various levels of television. We observe that television has the greatest influence on performance in a select countries, such as Lebanon, whilst it has the least impact in Slovenia. The confidence interval suggests that there is an uncertainty of the scores when a household does not own a television in the majority of the nations that participated in the PISA experiment in the year 2018.", fig.height=21, fig.width=12, fig.pos = "H", out.width="100%", layout="l-body"----
tv_plot


## -----------------------------------------------------------------------------
z_star_95 <- qnorm(0.975) 

book_math_read_sci_data <- student_country_data %>% 
  group_by(country_name, book)  %>% 
  dplyr::summarise(math_avg = 
            weighted.mean(math, 
              w = stu_wgt, na.rm = TRUE), 
           bk_lower = weighted.mean(math, 
              w = stu_wgt, na.rm = TRUE) - 
              z_star_95 * (sd(math, na.rm = TRUE)) /
              sqrt(length(math)), 
           bk_upper = weighted.mean(math, 
              w = stu_wgt, na.rm = TRUE) + 
              z_star_95 * (sd(math, na.rm = TRUE)) /
              sqrt(length(math)), .groups = "drop")  %>% 
  dplyr::mutate(book = recode_factor(book, 
                                     "0-10" = "1",
                                     "11-25" = "2", 
                                     "26-100" = "3",
                                     "101-200" = "4",
                                     "201-500" = "5",
                                     "more than 500" = "6",
                                     .ordered = TRUE)) %>% 
  na.omit() 

linear_model <- function(y, x){
  coef(lm(y ~ x))[2]
}


book_plot <- book_math_read_sci_data %>%
  group_by(country_name) %>%
  mutate(slope = linear_model(math_avg, book)) %>%
  ungroup() %>%
  mutate(country_name = fct_reorder(country_name, slope)) %>%
  ggplot(aes(x=as.numeric(book), y=math_avg)) + 
  geom_ribbon(aes(ymin = bk_lower, ymax = bk_upper),
                colour="orange", fill="orange", alpha=0.45) +
  geom_point(size=1.8) +
  geom_line(aes(group = country_name)) +
  facet_wrap(~country_name, ncol = 8, scales = "free") +
  theme(axis.text = element_blank()) +
  labs(x = "Number of Books",
       y = "Average Mathematics Score")


## ----book-plot, fig.cap ="Impact of the number of books on average math score. This graph indicates that the higher the number of books owned by a home, the greater the influence on student average math results. When compared to Luxembourg and Hungary, we discover that nations such as the Dominican Republic and Panama have a little lesser effect of books.", fig.height=25, fig.width=12, fig.pos = "H", out.width="100%", layout="l-body"----
book_plot


## -----------------------------------------------------------------------------
int_math_read_sci_data <- student_country_data %>% 
  group_by(country_name, internet) %>% 
  dplyr::summarise(math_avg = weighted.mean(math, w = stu_wgt, na.rm = TRUE), 
                   read_avg = weighted.mean(read, w = stu_wgt, na.rm = TRUE), 
                   sci_avg  =  weighted.mean(science, w = stu_wgt, na.rm = TRUE)) %>% 
  na.omit() 

comp_math_read_sci_data <- student_country_data %>% 
  group_by(country_name, computer) %>% 
  dplyr::summarise(math_avg = weighted.mean(math, w = stu_wgt, na.rm = TRUE), 
                   read_avg = weighted.mean(read, w = stu_wgt, na.rm = TRUE), 
                   sci_avg  =  weighted.mean(science, w = stu_wgt, na.rm = TRUE)) %>% 
  na.omit() 


computer_plot <- comp_math_read_sci_data %>%
  ggplot(aes(x=computer, 
             y= math_avg, 
             group = country_name)) +
    geom_point(color = "black",
               size=0.36) +
    geom_line(size = .27, 
              alpha = .45) +
    theme(legend.position = "none") +
    labs(x = "Possession of Computer",
         y = "Average Mathematics Score", 
         title = "Impact of Computers on Average Math Scores")


internet_plot <- int_math_read_sci_data %>%
  ggplot(aes(x=internet, 
             y= math_avg, 
             group = country_name )) +
    geom_point(color = "black",
               size=0.36) +
    geom_line(size = .27, 
              alpha = .45) +
    theme(legend.position = "none") +
    labs(x = "Access to Internet",
         y = "Average Mathematics Score", 
         title = "Impact of Internet on Average Math Scores")


## ----compint-plot, fig.cap ="Computers and the Internet are two of the most important inventions in the history of technology. In this figure, we observe the impact of owning a computer and having access to the internet on 15-year-old students all over the world. A remarkable finding from the plot is that all nations have higher scores in student performance when they own a computer and have access to the internet.", fig.width= 15, fig.height= 8, fig.pos = "H", out.width="100%", layout="l-body"----
computer_plot + internet_plot


## -----------------------------------------------------------------------------
# Load student data, and filter to country, cache a copy of the data
# to save downloading every time paper is knitted

if (!file.exists("data/student_all.rda")) {
  student_all <- load_student("all")
  save(student_all, file="data/student_all.rda")
} else {
  load("data/student_all.rda")
}

# Give countries their name, subset to four, and select only variables needed
student_country <- left_join(student_all,
                                  countrycode,
                                  by = "country") %>% 
  dplyr::filter(country_name %in% 
                  c("Australia", 
                    "New Zealand", 
                    "Qatar", 
                    "Indonesia", 
                    "Singapore", 
                    "Germany")) %>% 
  dplyr::select(year, country_name, math, read, science, stu_wgt) %>% 
  na.omit() %>%
  pivot_longer(c(math, read, science), names_to = "subject", values_to = "score")

# Compute the bootstrap confidence intervals, and cache result
if (!file.exists("data/all_bs_cf.rda")) {
  all_bootstrap <- map_dfr(1:100, ~{
    student_country %>%
    group_by(country_name, #year, 
             subject) %>%
    #sample_n(size = n(), replace = TRUE) %>%
    mutate(year = sample(year, replace=FALSE)) %>%
    group_by(country_name, year, 
             subject) %>%
    dplyr::summarise(
      avg = weighted.mean(score, w = stu_wgt, na.rm = TRUE), .groups = "drop") %>% 
    #ungroup() %>%
    mutate(boot_id = .x)
  })

  all_bootstrap_ci <- all_bootstrap %>%
    group_by(country_name, year, 
             subject) %>% 
    summarise(
      lower = min(avg), # sort(avg)[5],
      upper = max(avg), #sort(avg)[95], 
      .groups = "drop") 

  # compute original estimate of average and join
  all_avg <- student_country %>%
    group_by(country_name, year, subject) %>% 
    summarise(
      avg = weighted.mean(score, 
                          w = stu_wgt, na.rm = TRUE), 
      .groups = "drop")   
  
  all_bs_cf <- left_join(all_avg,
                      all_bootstrap_ci,
                      by = c("country_name", 
                             "year", 
                             "subject"))

  save(all_bs_cf, file="data/all_bs_cf.rda")

} else {
  load("data/all_bs_cf.rda")
}



## ----bs-plot, fig.cap ="Temporal trends in math, reading and science for a selection of countries. Line indicates average score across years, and the orange band is the permutation confidence interval assuming that there is no trend. ", fig.pos = "H", fig.width = 5, fig.height=12, out.width="70%", layout="l-body"----
all_bs_cf <- all_bs_cf %>%
  mutate(year = as.numeric(as.character(year)),
         country_name = factor(country_name, 
                 levels = c("Singapore", 
                          "Australia", 
                          "New Zealand", 
                          "Germany",
                          "Qatar", 
                          "Indonesia")))
ggplot(data = all_bs_cf, 
  aes(x = year, 
      y = avg)) +
  geom_ribbon(aes(x = year,
                    ymin = lower,
                    ymax = upper), 
              colour = "orange", fill = "orange", 
              alpha = 0.8) +
  geom_point(alpha = 0.1) +
  geom_line() +
  facet_grid(country_name~subject) +
  labs(
     x = "", 
     y = "Score") 



## ----anim-plot, eval = knitr::is_html_output(), fig.pos = "H", out.width="100%", layout="l-body-outset"----
#> student_country_anim <- left_join(student_all,
#>                                   countrycode,
#>                                   by = "country") %>%
#>   group_by(year) %>%
#>   ungroup() %>%
#>   dplyr::select(year, country_name, math, read, science, stu_wgt) %>%
#>   na.omit()
#> 
#> student_country_anim_avg <- student_country_anim %>%
#> group_by(country_name, year) %>%
#> dplyr::summarise(math_avg = weighted.mean(math, w = stu_wgt, na.rm = TRUE),
#>                    read_avg = weighted.mean(read, w = stu_wgt, na.rm = TRUE),
#>                    sci_avg  =  weighted.mean(science, w = stu_wgt, na.rm = TRUE)) %>%
#> ungroup()
#> 
#> student_country_anim_avg$year <- as.integer(student_country_anim_avg$year)
#> 
#> 
#> #animate
#> ggplot(student_country_anim_avg,
#>        aes(math_avg, sci_avg,
#>            color = country_name, )) +
#>   geom_text(aes(label = country_name),
#>             check_overlap = TRUE) +
#>   theme(legend.position = "none") +
#>   transition_time(year)   +
#>   labs(title = 'Year: {frame_time}',
#>        x = "Average math Scores",
#>        y = "Average Science Scores")

